// Generated by @specodec/typespec-emitter-swift. DO NOT EDIT.
import Foundation
import Specodec

public struct UnionFieldHolder {
    public var shape: Shape
    public var id: Ident
}

public func writeUnionFieldHolder(_ w: any SpecWriter, _ obj: UnionFieldHolder) {
    w.beginObject(2)
    w.writeField("shape"); writeShape(w, obj.shape)
    w.writeField("id"); writeIdent(w, obj.id)
    w.endObject()
}

public func decodeUnionFieldHolder(_ r: any SpecReader) throws -> UnionFieldHolder {
    var shape: Shape!
    var id: Ident!
    try r.beginObject()
    while try r.hasNextField() {
        switch try r.readFieldName() {
        case "shape": shape = try decodeShape(r)
        case "id": id = try decodeIdent(r)
        default: try r.skip()
        }
    }
    try r.endObject()
    return UnionFieldHolder(shape: shape, id: id)
}

public let UnionFieldHolderCodec = SpecCodec<UnionFieldHolder>(
    encode: { w, obj in writeUnionFieldHolder(w, obj) },
    decode: { r throws in try decodeUnionFieldHolder(r) }
)

public struct OptUnionFieldHolder {
    public var shape: Shape?
    public var name: String
    public init() {
        shape = nil
        name = ""
    }
    public init(shape: Shape? = nil, name: String) {
        self.shape = shape; self.name = name
    }
}

public func writeOptUnionFieldHolder(_ w: any SpecWriter, _ obj: OptUnionFieldHolder) {
    var fieldCount = 1
    if obj.shape != nil { fieldCount += 1 }
    w.beginObject(fieldCount)
    if let shape = obj.shape { w.writeField("shape"); writeShape(w, shape) }
    w.writeField("name"); w.writeString(obj.name)
    w.endObject()
}

public func decodeOptUnionFieldHolder(_ r: any SpecReader) throws -> OptUnionFieldHolder {
    var shape: Shape? = nil
    var name: String = ""
    try r.beginObject()
    while try r.hasNextField() {
        switch try r.readFieldName() {
        case "shape": shape = try { () throws -> Shape? in if try r.isNull() { try r.readNull(); return nil }; return try decodeShape(r) }()
        case "name": name = try r.readString()
        default: try r.skip()
        }
    }
    try r.endObject()
    return OptUnionFieldHolder(shape: shape, name: name)
}

public let OptUnionFieldHolderCodec = SpecCodec<OptUnionFieldHolder>(
    encode: { w, obj in writeOptUnionFieldHolder(w, obj) },
    decode: { r throws in try decodeOptUnionFieldHolder(r) }
)

public struct UnionArrayHolder {
    public var shapes: [Shape]
    public init() {
        shapes = []
    }
    public init(shapes: [Shape]) {
        self.shapes = shapes
    }
}

public func writeUnionArrayHolder(_ w: any SpecWriter, _ obj: UnionArrayHolder) {
    w.beginObject(1)
    w.writeField("shapes"); w.beginArray(obj.shapes.count); for item in obj.shapes { w.nextElement(); writeShape(w, item) }; w.endArray()
    w.endObject()
}

public func decodeUnionArrayHolder(_ r: any SpecReader) throws -> UnionArrayHolder {
    var shapes: [Shape] = []
    try r.beginObject()
    while try r.hasNextField() {
        switch try r.readFieldName() {
        case "shapes": shapes = try { () throws -> [Shape] in var arr: [Shape] = []; try r.beginArray(); while try r.hasNextElement() { arr.append(try decodeShape(r)) }; try r.endArray(); return arr }()
        default: try r.skip()
        }
    }
    try r.endObject()
    return UnionArrayHolder(shapes: shapes)
}

public let UnionArrayHolderCodec = SpecCodec<UnionArrayHolder>(
    encode: { w, obj in writeUnionArrayHolder(w, obj) },
    decode: { r throws in try decodeUnionArrayHolder(r) }
)

public struct UnionMixedHolder {
    public var result: ResultMsg
    public var tag: Tagged
    public var count: Int32
}

public func writeUnionMixedHolder(_ w: any SpecWriter, _ obj: UnionMixedHolder) {
    w.beginObject(3)
    w.writeField("result"); writeResultMsg(w, obj.result)
    w.writeField("tag"); writeTagged(w, obj.tag)
    w.writeField("count"); w.writeInt32(obj.count)
    w.endObject()
}

public func decodeUnionMixedHolder(_ r: any SpecReader) throws -> UnionMixedHolder {
    var result: ResultMsg!
    var tag: Tagged!
    var count: Int32 = 0
    try r.beginObject()
    while try r.hasNextField() {
        switch try r.readFieldName() {
        case "result": result = try decodeResultMsg(r)
        case "tag": tag = try decodeTagged(r)
        case "count": count = try r.readInt32()
        default: try r.skip()
        }
    }
    try r.endObject()
    return UnionMixedHolder(result: result, tag: tag, count: count)
}

public let UnionMixedHolderCodec = SpecCodec<UnionMixedHolder>(
    encode: { w, obj in writeUnionMixedHolder(w, obj) },
    decode: { r throws in try decodeUnionMixedHolder(r) }
)

public struct UnionScalarHolder {
    public var id: Ident
    public var sc: ScalarUnion
    public var label: String
}

public func writeUnionScalarHolder(_ w: any SpecWriter, _ obj: UnionScalarHolder) {
    w.beginObject(3)
    w.writeField("id"); writeIdent(w, obj.id)
    w.writeField("sc"); writeScalarUnion(w, obj.sc)
    w.writeField("label"); w.writeString(obj.label)
    w.endObject()
}

public func decodeUnionScalarHolder(_ r: any SpecReader) throws -> UnionScalarHolder {
    var id: Ident!
    var sc: ScalarUnion!
    var label: String = ""
    try r.beginObject()
    while try r.hasNextField() {
        switch try r.readFieldName() {
        case "id": id = try decodeIdent(r)
        case "sc": sc = try decodeScalarUnion(r)
        case "label": label = try r.readString()
        default: try r.skip()
        }
    }
    try r.endObject()
    return UnionScalarHolder(id: id, sc: sc, label: label)
}

public let UnionScalarHolderCodec = SpecCodec<UnionScalarHolder>(
    encode: { w, obj in writeUnionScalarHolder(w, obj) },
    decode: { r throws in try decodeUnionScalarHolder(r) }
)

public enum Shape {
    case circle(Coord)
    case rect(Range32)
}

public func writeShape(_ w: any SpecWriter, _ obj: Shape) {
    w.beginObject(1)
    switch obj {
    case .circle(let v): w.writeField("circle"); writeCoord(w, v)
    case .rect(let v): w.writeField("rect"); writeRange32(w, v)
    }
    w.endObject()
}

public func decodeShape(_ r: any SpecReader) throws -> Shape {
    try r.beginObject()
    guard try r.hasNextField() else { try r.endObject(); throw SCodecError(code: "unknownField", message: "empty union") }
    let field = try r.readFieldName()
    let result: Shape
    switch field {
    case "circle": result = .circle(try decodeCoord(r))
    case "rect": result = .rect(try decodeRange32(r))
    default: throw SCodecError(code: "unknownField", message: "unknown variant \(field)")
    }
    while try r.hasNextField() { _ = try r.readFieldName(); try r.skip() }
    try r.endObject()
    return result
}

public let ShapeCodec = SpecCodec<Shape>(
    encode: { w, obj in writeShape(w, obj) },
    decode: { r throws in try decodeShape(r) }
)

public enum Ident {
    case name(String)
    case number(Int32)
}

public func writeIdent(_ w: any SpecWriter, _ obj: Ident) {
    w.beginObject(1)
    switch obj {
    case .name(let v): w.writeField("name"); w.writeString(v)
    case .number(let v): w.writeField("number"); w.writeInt32(v)
    }
    w.endObject()
}

public func decodeIdent(_ r: any SpecReader) throws -> Ident {
    try r.beginObject()
    guard try r.hasNextField() else { try r.endObject(); throw SCodecError(code: "unknownField", message: "empty union") }
    let field = try r.readFieldName()
    let result: Ident
    switch field {
    case "name": result = .name(try r.readString())
    case "number": result = .number(try r.readInt32())
    default: throw SCodecError(code: "unknownField", message: "unknown variant \(field)")
    }
    while try r.hasNextField() { _ = try r.readFieldName(); try r.skip() }
    try r.endObject()
    return result
}

public let IdentCodec = SpecCodec<Ident>(
    encode: { w, obj in writeIdent(w, obj) },
    decode: { r throws in try decodeIdent(r) }
)

public enum ResultMsg {
    case ok(String)
    case err(Label)
}

public func writeResultMsg(_ w: any SpecWriter, _ obj: ResultMsg) {
    w.beginObject(1)
    switch obj {
    case .ok(let v): w.writeField("ok"); w.writeString(v)
    case .err(let v): w.writeField("err"); writeLabel(w, v)
    }
    w.endObject()
}

public func decodeResultMsg(_ r: any SpecReader) throws -> ResultMsg {
    try r.beginObject()
    guard try r.hasNextField() else { try r.endObject(); throw SCodecError(code: "unknownField", message: "empty union") }
    let field = try r.readFieldName()
    let result: ResultMsg
    switch field {
    case "ok": result = .ok(try r.readString())
    case "err": result = .err(try decodeLabel(r))
    default: throw SCodecError(code: "unknownField", message: "unknown variant \(field)")
    }
    while try r.hasNextField() { _ = try r.readFieldName(); try r.skip() }
    try r.endObject()
    return result
}

public let ResultMsgCodec = SpecCodec<ResultMsg>(
    encode: { w, obj in writeResultMsg(w, obj) },
    decode: { r throws in try decodeResultMsg(r) }
)

public enum Tagged {
    case tag(String)
    case score(Double)
    case active(Bool)
}

public func writeTagged(_ w: any SpecWriter, _ obj: Tagged) {
    w.beginObject(1)
    switch obj {
    case .tag(let v): w.writeField("tag"); w.writeString(v)
    case .score(let v): w.writeField("score"); w.writeFloat64(v)
    case .active(let v): w.writeField("active"); w.writeBool(v)
    }
    w.endObject()
}

public func decodeTagged(_ r: any SpecReader) throws -> Tagged {
    try r.beginObject()
    guard try r.hasNextField() else { try r.endObject(); throw SCodecError(code: "unknownField", message: "empty union") }
    let field = try r.readFieldName()
    let result: Tagged
    switch field {
    case "tag": result = .tag(try r.readString())
    case "score": result = .score(try r.readFloat64())
    case "active": result = .active(try r.readBool())
    default: throw SCodecError(code: "unknownField", message: "unknown variant \(field)")
    }
    while try r.hasNextField() { _ = try r.readFieldName(); try r.skip() }
    try r.endObject()
    return result
}

public let TaggedCodec = SpecCodec<Tagged>(
    encode: { w, obj in writeTagged(w, obj) },
    decode: { r throws in try decodeTagged(r) }
)

public enum ScalarUnion {
    case s(String)
    case i(Int32)
    case f(Double)
    case b(Bool)
}

public func writeScalarUnion(_ w: any SpecWriter, _ obj: ScalarUnion) {
    w.beginObject(1)
    switch obj {
    case .s(let v): w.writeField("s"); w.writeString(v)
    case .i(let v): w.writeField("i"); w.writeInt32(v)
    case .f(let v): w.writeField("f"); w.writeFloat64(v)
    case .b(let v): w.writeField("b"); w.writeBool(v)
    }
    w.endObject()
}

public func decodeScalarUnion(_ r: any SpecReader) throws -> ScalarUnion {
    try r.beginObject()
    guard try r.hasNextField() else { try r.endObject(); throw SCodecError(code: "unknownField", message: "empty union") }
    let field = try r.readFieldName()
    let result: ScalarUnion
    switch field {
    case "s": result = .s(try r.readString())
    case "i": result = .i(try r.readInt32())
    case "f": result = .f(try r.readFloat64())
    case "b": result = .b(try r.readBool())
    default: throw SCodecError(code: "unknownField", message: "unknown variant \(field)")
    }
    while try r.hasNextField() { _ = try r.readFieldName(); try r.skip() }
    try r.endObject()
    return result
}

public let ScalarUnionCodec = SpecCodec<ScalarUnion>(
    encode: { w, obj in writeScalarUnion(w, obj) },
    decode: { r throws in try decodeScalarUnion(r) }
)

public enum OptUnionHolder {
    case shape(Shape)
    case id(Ident)
}

public func writeOptUnionHolder(_ w: any SpecWriter, _ obj: OptUnionHolder) {
    w.beginObject(1)
    switch obj {
    case .shape(let v): w.writeField("shape"); writeShape(w, v)
    case .id(let v): w.writeField("id"); writeIdent(w, v)
    }
    w.endObject()
}

public func decodeOptUnionHolder(_ r: any SpecReader) throws -> OptUnionHolder {
    try r.beginObject()
    guard try r.hasNextField() else { try r.endObject(); throw SCodecError(code: "unknownField", message: "empty union") }
    let field = try r.readFieldName()
    let result: OptUnionHolder
    switch field {
    case "shape": result = .shape(try decodeShape(r))
    case "id": result = .id(try decodeIdent(r))
    default: throw SCodecError(code: "unknownField", message: "unknown variant \(field)")
    }
    while try r.hasNextField() { _ = try r.readFieldName(); try r.skip() }
    try r.endObject()
    return result
}

public let OptUnionHolderCodec = SpecCodec<OptUnionHolder>(
    encode: { w, obj in writeOptUnionHolder(w, obj) },
    decode: { r throws in try decodeOptUnionHolder(r) }
)

public enum MixedUnion {
    case point(Coord)
    case label(String)
    case count(Int32)
}

public func writeMixedUnion(_ w: any SpecWriter, _ obj: MixedUnion) {
    w.beginObject(1)
    switch obj {
    case .point(let v): w.writeField("point"); writeCoord(w, v)
    case .label(let v): w.writeField("label"); w.writeString(v)
    case .count(let v): w.writeField("count"); w.writeInt32(v)
    }
    w.endObject()
}

public func decodeMixedUnion(_ r: any SpecReader) throws -> MixedUnion {
    try r.beginObject()
    guard try r.hasNextField() else { try r.endObject(); throw SCodecError(code: "unknownField", message: "empty union") }
    let field = try r.readFieldName()
    let result: MixedUnion
    switch field {
    case "point": result = .point(try decodeCoord(r))
    case "label": result = .label(try r.readString())
    case "count": result = .count(try r.readInt32())
    default: throw SCodecError(code: "unknownField", message: "unknown variant \(field)")
    }
    while try r.hasNextField() { _ = try r.readFieldName(); try r.skip() }
    try r.endObject()
    return result
}

public let MixedUnionCodec = SpecCodec<MixedUnion>(
    encode: { w, obj in writeMixedUnion(w, obj) },
    decode: { r throws in try decodeMixedUnion(r) }
)

public enum NestedUnion {
    case result(ResultMsg)
    case shape(Shape)
}

public func writeNestedUnion(_ w: any SpecWriter, _ obj: NestedUnion) {
    w.beginObject(1)
    switch obj {
    case .result(let v): w.writeField("result"); writeResultMsg(w, v)
    case .shape(let v): w.writeField("shape"); writeShape(w, v)
    }
    w.endObject()
}

public func decodeNestedUnion(_ r: any SpecReader) throws -> NestedUnion {
    try r.beginObject()
    guard try r.hasNextField() else { try r.endObject(); throw SCodecError(code: "unknownField", message: "empty union") }
    let field = try r.readFieldName()
    let result: NestedUnion
    switch field {
    case "result": result = .result(try decodeResultMsg(r))
    case "shape": result = .shape(try decodeShape(r))
    default: throw SCodecError(code: "unknownField", message: "unknown variant \(field)")
    }
    while try r.hasNextField() { _ = try r.readFieldName(); try r.skip() }
    try r.endObject()
    return result
}

public let NestedUnionCodec = SpecCodec<NestedUnion>(
    encode: { w, obj in writeNestedUnion(w, obj) },
    decode: { r throws in try decodeNestedUnion(r) }
)
