FROM docker.io/library/swift:latest AS runner
WORKDIR /app
ARG HTTP_PROXY HTTPS_PROXY http_proxy https_proxy ALL_PROXY all_proxy
ENV http_proxy=${HTTP_PROXY} https_proxy=${HTTPS_PROXY} HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTPS_PROXY} ALL_PROXY=${ALL_PROXY}

COPY --from=emit_swift_src Package.swift ./
COPY --from=specodec-runtime-swift . /specodec-swift/
COPY --from=emit_swift_src Sources/ Sources/
COPY --from=emit_gen TestServiceTypes.swift Sources/run_swift/
COPY --from=emit_swift_src Sources/run_swift/dump_emit.swift Sources/run_swift/

COPY vectors/ /app/vectors/
RUN mkdir -p /app/output_emit_swift
ENV VEC_DIR=/app/vectors OUT_DIR=/app/output_emit_swift
RUN --mount=type=cache,target=/root/.cache/org.swift.swiftpm \
    swift build -c release && .build/release/run_swift
